# Taken from URL. https://hub.docker.com/_/mysql/
version: '3'
services:
    mysql:
        image: mysql:8
        ports:
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - /tmp/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=example
            - MYSQL_DATABASE=testing
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
