# Taken from URL: https://github.com/bitnami/bitnami-docker-kafka
version: '3'
services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1

            # See URL: https://github.com/bitnami/bitnami-docker-kafka#accessing-apache-kafka-with-internal-and-external-clients
            - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_DELETE_TOPIC_ENABLE=true
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    kafka-ui:
        image: provectuslabs/kafka-ui
        ports:
            - '8080:8080'
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
            - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
        depends_on:
            - kafka
    kafdrop:
        image: obsidiandynamics/kafdrop
        ports:
            - '9001:9001'
        environment:
            - KAFKA_BROKERCONNECT=kafka:29092
            - JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
        depends_on:
            - kafka
