version: '3'
services:
    redis:
        image: docker.io/bitnami/redis:latest
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6380:6380'
        volumes:
            - 'redis_data:/bitnami/redis/data'
volumes:
    redis_data:
        driver: local
